

service: java-lambda-latency-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  
plugins:
  - serverless-dotenv-plugin

functions:
  hello:
    handler: handler.hello
    # default is 6, this fn can take a few min to run though so we bump the timeout way up
    timeout: 240 
    # optional, in MB, default is 1024
    memorySize: 256
    events:
    - schedule: rate(5 minutes)
